=== EmptyJ/Archipelago-SC2-data/schemas/SchemaUpgradeData.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Catalog">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element name="CUpgrade" type="CUpgrade"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="ids_within_a_document_must_be_unique">
            <xs:selector xpath="CUpgrade"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>
    
    <xs:complexType name="CUpgrade">
        <xs:sequence minOccurs="0">
            <xs:group ref="upgrade_elements" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="default" type="ZeroOrOne"/>
        <xs:attribute name="parent" type="xs:string"/>
    </xs:complexType>

    <xs:group name="upgrade_elements">
        <xs:choice>
            <!-- Further elements seen elsewhere -->
            <xs:element name="Name" type="value_string"/>
            <xs:element name="Race" type="value_race"/>
            <xs:element name="EditorCategories" type="EditorCategories"/>
            <xs:element name="LeaderAlias" type="value_string"/>
            <xs:element name="DataCollection" type="value_string"/>
            <xs:element name="BonusTimePerLevel" type="value_float"/>
            <xs:element name="LeaderLevel" type="value_int"/>
            <xs:element name="Alert" type="value_string"/>
            <xs:element name="Icon" type="value_string"/>
            <xs:element name="MaxLevel" type="value_int"/>
            <xs:element name="WebPriority" type="value_int"/>
            <xs:element name="InfoTooltipPriority" type="value_string"/>
            <xs:element name="LeaderAlias" type="value_string"/>
            <xs:element name="LeaderPriority" type="value_int"/>
            <xs:element name="ScoreAmount" type="value_int"/>
            <xs:element name="ScoreCount" type="value_string"/>
            <xs:element name="ScoreResult" type="value_string"/>
            <xs:element name="ScoreValue" type="value_string"/>
            <!-- Flag types -->
            <xs:element name="Flags" type="binary_flags"/>
            <xs:element name="EnumExcludedUserFlags" type="user_flags"/>
            <xs:element name="EnumRequiredUserFlags" type="user_flags"/>
            <xs:element name="BonusResourcePerLevel" type="resource_type_to_val"/>
            <!-- Array types -->
            <xs:element name="EffectArray" type="array_ref_val"/>
            <xs:element name="EffectArrayTemplate" type="array_ref_val"/>
            <xs:element name="AffectedUnitArray" type="array_value_string"/>
            <xs:element name="TechAliasArray" type="array_value_string"/>
            <xs:element name="LevelButton" type="array_value_string"/>
            <xs:element name="LevelRequirements" type="array_value_string"/>
            <xs:element name="UnitAllowed" type="array_value_string"/>
            <xs:element name="UnitDisallowed" type="array_value_string"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="binary_flags">
        <xs:attribute name="index" type="xs:string" use="required"/>
        <xs:attribute name="value" type="ZeroOrOne" use="required"/>
    </xs:complexType>
    <xs:complexType name="user_flags">
        <xs:attribute name="index" type="xs:string" use="required"/>
        <xs:attribute name="value" type="user_flag_option" use="required"/>
    </xs:complexType>
    <xs:complexType name="resource_type_to_val">
        <xs:attribute name="index" type="resource_type" use="required"/>
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="EditorCategories">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="value_int">
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>
    <xs:complexType name="value_float">
        <xs:attribute name="value" type="xs:float" use="required"/>
    </xs:complexType>
    <xs:complexType name="value_string">
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="value_race">
        <xs:attribute name="value" type="race" use="required"/>
    </xs:complexType>
    <xs:complexType name="array_value_string">
        <xs:attribute name="index" type="xs:string"/>
        <xs:attribute name="value" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="array_ref_val">
        <xs:attribute name="index" type="xs:string" use="optional"/>
        <xs:attribute name="Operation" type="operation" use="optional"/>
        <xs:attribute name="Reference" type="xs:string" use="required"/>
        <xs:attribute name="Value" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="race">
        <xs:restriction base="xs:string">
            <!-- Defaults to Add when nothing specified -->
            <xs:enumeration value="Neut"/>
            <xs:enumeration value="Prot"/>
            <xs:enumeration value="Terr"/>
            <xs:enumeration value="Zerg"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="operation">
        <xs:restriction base="xs:string">
            <!-- Defaults to Add when nothing specified -->
            <xs:enumeration value="AddBaseMultiply"/>
            <xs:enumeration value="Divide"/>
            <xs:enumeration value="Multiply"/>
            <xs:enumeration value="Set"/>
            <xs:enumeration value="Subtract"/>
            <xs:enumeration value="SubtractBaseMultiply"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="user_flag_option">
        <xs:restriction base="xs:string">
            <!-- Defaults to Add when nothing specified -->
            <xs:enumeration value="Ancient"/>
            <xs:enumeration value="ArmyUnit"/>
            <xs:enumeration value="Bridge"/>
            <xs:enumeration value="Building"/>
            <xs:enumeration value="CanSleep"/>
            <xs:enumeration value="Destructible"/>
            <xs:enumeration value="Hero"/>
            <xs:enumeration value="Item"/>
            <xs:enumeration value="Powerup"/>
            <xs:enumeration value="Projectile"/>
            <xs:enumeration value="Tree"/>
            <xs:enumeration value="Unit"/>
            <xs:enumeration value="User14"/>
            <xs:enumeration value="User15"/>
            <xs:enumeration value="User16"/>
            <xs:enumeration value="Ward"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="resource_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Minerals"/>
            <xs:enumeration value="Vespene"/>
            <xs:enumeration value="Terrazine"/>
            <xs:enumeration value="Custom"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ZeroOrOne">
        <xs:restriction base="xs:int">
            <xs:enumeration value="0"/>
            <xs:enumeration value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UseOrShow">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Use"/>
            <xs:enumeration value="Show"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== EmptyJ/Archipelago-SC2-data/Mods/ArchipelagoPlayerLotVPrologue.SC2Mod/Base.SC2Data/GameData/UpgradeData.xml
<?xml version="1.0" encoding="utf-8" ?>
<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../schemas/SchemaUpgradeData.xsd">
    <CUpgrade id="AP_BaseProtossGroundWeapons">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsQuatro">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsPreplacedNoBuild">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsLevel1">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
        <EffectArray Operation="Set" Reference="Weapon,PrologueZeratul,Icon" Value="Assets\Textures\btn-upgrade-protoss-groundweaponslevel1.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsLevel2">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
        <EffectArray Operation="Set" Reference="Weapon,PrologueZeratul,Icon" Value="Assets\Textures\btn-upgrade-protoss-groundweaponslevel2.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsLevel3">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
        <EffectArray Operation="Set" Reference="Weapon,PrologueZeratul,Icon" Value="Assets\Textures\btn-upgrade-protoss-groundweaponslevel3.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsLevel3">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
        <EffectArray Operation="Set" Reference="Weapon,PrologueZeratul,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-groundarmorlevel4.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundWeaponsLevel5">
        <!-- Override -->
        <EffectArray Reference="Weapon,PrologueZeratul,Level" Value="1"/>
        <EffectArray Reference="Effect,PrologueZeratul,Amount" Value="5"/>
        <EffectArray Operation="Set" Reference="Weapon,PrologueZeratul,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-groundarmorlevel5.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_BaseProtossGroundArmors">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsQuatro">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsPreplacedNoBuild">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsLevel1">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-groundarmorlevel1.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsLevel2">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-groundarmorlevel2.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsLevel3">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-groundarmorlevel3.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsLevel4">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,LifeArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-groundarmorlevel4.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossGroundArmorsLevel5">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,LifeArmorLevel" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,LifeArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-groundarmorlevel5.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_BaseProtossShields">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsQuatro">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsPreplacedNoBuild">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsLevel1">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>

        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,ShieldArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-shieldslevel1.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsLevel2">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>

        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,ShieldArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-shieldslevel2.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsLevel3">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>

        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,ShieldArmorIcon" Value="Assets\Textures\btn-upgrade-protoss-shieldslevel3.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsLevel4">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>

        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,ShieldArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-shieldslevel4.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ProtossShieldsLevel5">
        <!-- Override -->
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmor" Value="1.000000"/>
        <EffectArray Reference="Unit,PrologueZeratul,ShieldArmorLevel" Value="1"/>

        <EffectArray Operation="Set" Reference="Actor,PrologueZeratul,ShieldArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-protoss-shieldslevel5.dds"/>
    </CUpgrade>
</Catalog>

=== EmptyJ/Archipelago-SC2-data/Maps/ArchipelagoCampaign/LotV/ap_the_essence_of_eternity.SC2Map/Base.SC2Data/GameData/UpgradeData.xml
<?xml version="1.0" encoding="utf-8" ?>
<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../schemas/SchemaUpgradeData.xsd">
    <CUpgrade id="AP_BaseZergGroundArmors">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_BaseZergMissileWeapons">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergGroundArmorsLevel1">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,ZaGara,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-zerg-groundcarapace-level1.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergGroundArmorsLevel2">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,ZaGara,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-zerg-groundcarapace-level2.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergGroundArmorsLevel3">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,ZaGara,LifeArmorIcon" Value="Assets\Textures\btn-upgrade-zerg-groundcarapace-level3.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergGroundArmorsLevel4">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,ZaGara,LifeArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-groundcarapace-level4.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergGroundArmorsLevel5">
        <!-- Override -->
        <EffectArray Reference="Unit,ZaGara,LifeArmorLevel" Value="1"/>
        <EffectArray Reference="Unit,ZaGara,LifeArmor" Value="1"/>
        <EffectArray Operation="Set" Reference="Actor,ZaGara,LifeArmorIcon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-groundcarapace-level5.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergMissileWeaponsLevel1">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraAcidSpines,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level1.dds"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraTalons,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level1.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergMissileWeaponsLevel2">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraAcidSpines,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level2.dds"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraTalons,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level2.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergMissileWeaponsLevel3">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraAcidSpines,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level3.dds"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraTalons,Icon" Value="Assets\Textures\btn-upgrade-zerg-missileattacks-level3.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergMissileWeaponsLevel4">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraAcidSpines,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-missileattacks-level4.dds"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraTalons,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-missileattacks-level4.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_ZergMissileWeaponsLevel5">
        <!-- Override -->
        <EffectArray Reference="Effect,ZaGaraAcidSpinesDamage,Amount" Value="3"/>
        <EffectArray Reference="Weapon,ZaGaraAcidSpines,Level" Value="1"/>
        <EffectArray Reference="Effect,ZaGaraTalonsDamage,Amount" Value="2"/>
        <EffectArray Reference="Weapon,ZaGaraTalons,Level" Value="1"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraAcidSpines,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-missileattacks-level5.dds"/>
        <EffectArray Operation="Set" Reference="Weapon,ZaGaraTalons,Icon" Value="AP\Assets\Custom\Textures\btn-upgrade-zerg-missileattacks-level5.dds"/>
    </CUpgrade>
    <CUpgrade id="AP_K5CreepBonuses">
        <EffectArray Reference="Unit,ZaGara,AttackSpeedMultiplierCreep" Value="0.3"/>
        <EffectArray Reference="Unit,ZaGara,LifeRegenRateCreep" Value="0.820200"/>
        <EffectArray Reference="Unit,ZaGaraBurrowed,LifeRegenRateCreep" Value="0.820200"/>
    </CUpgrade>
</Catalog>
